sudo: required

services:
- docker

language: php

addons:
  apt:
    packages:
    - expect

php:
- '7.0'
- '7.1'
- '7.2'
- nightly

before_script:
- sudo apt-get update
- sudo apt-get install -y expect
- docker pull evilfreelancer/docker-routeros:6.42
- docker pull evilfreelancer/docker-routeros:latest
- docker run -d -p 12222:22 -p 18728:8728 -p 18729:8729 -ti evilfreelancer/docker-routeros:6.42
- docker run -d -p 2222:22 -p 8728:8728 -p 8729:8729 -ti evilfreelancer/docker-routeros:latest
- docker ps -a
- sleep 30
- ./preconfig.sh 12222 || true
- ./preconfig.sh 2222  || true
- composer self-update
- composer install --prefer-source --no-interaction --dev

script:
- vendor/bin/phpunit
